#if DEVTOOLS_ENABLED
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;

namespace PureDOTS.Runtime.Devtools
{
    /// <summary>
    /// Spawn pattern types.
    /// </summary>
    public enum SpawnPattern : byte
    {
        Point = 0,
        Line = 1,
        Circle = 2,
        Grid = 3,
        Scatter = 4
    }

    /// <summary>
    /// Spawn request flags.
    /// </summary>
    [System.Flags]
    public enum SpawnFlags : byte
    {
        None = 0,
        ValidateOnly = 1,
        SnapToGround = 2,
        AllowOverlap = 4,
        AtCursor = 8,
        RespectTerrain = 16,
        NavmeshOnly = 32
    }

    /// <summary>
    /// Single entity spawn request.
    /// </summary>
    public struct SpawnRequest : IComponentData
    {
        public int PrototypeId;
        public int Count;
        public float3 Position;
        public quaternion Rotation;
        public SpawnPattern Pattern;
        public float RadiusOrSpread;
        public int Columns; // For Grid/Line patterns
        public uint Seed;
        public SpawnFlags Flags;
        public byte OwnerPlayerId;
    }

    /// <summary>
    /// Stat override for spawned entities.
    /// </summary>
    public struct StatOverride : IBufferElementData
    {
        public FixedString64Bytes Name;
        public float Value;
    }

    /// <summary>
    /// Spawn candidate pose generated by pattern solver.
    /// </summary>
    public struct SpawnCandidate : IBufferElementData
    {
        public float3 Position;
        public quaternion Rotation;
        public int PrototypeId;
        public byte IsValid;
    }

    /// <summary>
    /// Validation result for a spawn candidate.
    /// </summary>
    public enum ValidationFailureReason : byte
    {
        None = 0,
        TooSteep = 1,
        OverlapsExisting = 2,
        OutOfBounds = 3,
        ForbiddenVolume = 4,
        NotOnNavmesh = 5,
        Other = 255
    }

    /// <summary>
    /// Validation result attached to spawn candidates.
    /// </summary>
    public struct SpawnValidationResult : IBufferElementData
    {
        public ValidationFailureReason FailureReason;
        public FixedString128Bytes FailureMessage;
    }
}
#endif























