using PureDOTS.Runtime.Components;
using PureDOTS.Runtime.Stats;
using Unity.Burst;
using Unity.Collections;
using Unity.Entities;

namespace PureDOTS.Systems.Stats
{
    /// <summary>
    /// System for accumulating XP and applying stat progression.
    /// Ensures deterministic math and logging for rewind compatibility.
    /// </summary>
    [BurstCompile]
    [UpdateInGroup(typeof(SimulationSystemGroup))]
    public partial struct StatXPAccumulationSystem : ISystem
    {
        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
            state.RequireForUpdate<TimeState>();
        }

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            // This system will process XP gain/spend commands from command log
            // For now, it's a placeholder that will be extended with actual XP accumulation logic
            // when XP gain events are generated by gameplay systems.
        }
    }

    /// <summary>
    /// Helper methods for XP accumulation operations.
    /// </summary>
    public static class StatXPHelpers
    {
        /// <summary>
        /// Gain XP for a specific stat type. Records to command log for rewind compatibility.
        /// </summary>
        public static void GainXP(
            ref SystemState state,
            Entity targetEntity,
            StatType statType,
            float xpAmount,
            uint currentTick)
        {
            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            var commandLog = state.EntityManager.GetBuffer<StatXPCommandLogEntry>(targetEntity);
            commandLog.Add(new StatXPCommandLogEntry
            {
                Tick = currentTick,
                TargetEntity = targetEntity,
                StatType = statType,
                XPAmount = xpAmount,
                ChangeType = StatXPChangeType.Gain
            });

            // Apply XP gain immediately
            ApplyXPChange(ref state, targetEntity, statType, xpAmount);
        }

        /// <summary>
        /// Spend XP for a specific stat type. Records to command log.
        /// </summary>
        public static void SpendXP(
            ref SystemState state,
            Entity targetEntity,
            StatType statType,
            float xpAmount,
            uint currentTick)
        {
            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            var commandLog = state.EntityManager.GetBuffer<StatXPCommandLogEntry>(targetEntity);
            commandLog.Add(new StatXPCommandLogEntry
            {
                Tick = currentTick,
                TargetEntity = targetEntity,
                StatType = statType,
                XPAmount = -xpAmount,
                ChangeType = StatXPChangeType.Spend
            });

            // Apply XP spend immediately
            ApplyXPChange(ref state, targetEntity, statType, -xpAmount);
        }

        /// <summary>
        /// Reset XP for a specific stat type. Records to command log.
        /// </summary>
        public static void ResetXP(
            ref SystemState state,
            Entity targetEntity,
            StatType statType,
            uint currentTick)
        {
            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            if (!state.EntityManager.HasBuffer<StatXPCommandLogEntry>(targetEntity))
            {
                return;
            }

            var commandLog = state.EntityManager.GetBuffer<StatXPCommandLogEntry>(targetEntity);
            commandLog.Add(new StatXPCommandLogEntry
            {
                Tick = currentTick,
                TargetEntity = targetEntity,
                StatType = statType,
                XPAmount = 0f,
                ChangeType = StatXPChangeType.Reset
            });

            // Reset stat to base value (implementation depends on game-specific logic)
        }

        private static void ApplyXPChange(ref SystemState state, Entity targetEntity, StatType statType, float xpDelta)
        {
            // Apply XP change to appropriate stat component
            // This is a simplified version - actual implementation would need to:
            // 1. Check if entity has IndividualStats or PhysiqueFinesseWill
            // 2. Apply XP to appropriate stat
            // 3. Check for level-ups and apply stat increases
            // 4. Update StatHistorySample buffer

            // Placeholder - actual implementation will be game-specific
        }
    }
}

